# Generated by Django 3.2.11 on 2022-11-01 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_requestdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestdata',
            old_name='post',
            new_name='img',
        ),
    ]
