# Generated by Django 3.2.11 on 2022-11-01 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_post_requestdata_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestdata',
            name='img',
            field=models.FileField(upload_to='learVue/post_image/'),
        ),
    ]
